# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,

steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Pull docker cache
  entrypoint: 'bash'
  args:
  - '-c'
  - |
   docker pull gcr.io/$PROJECT_ID/dbt-demo:latest || exit 0

- name: gcr.io/cloud-builders/docker
  id: Build Airflow DAGs Builder
  args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/dbt-demo',
      '--cache-from', 'gcr.io/$PROJECT_ID/dbt-demo:latest',
      './'
    ]

- name: gcr.io/cloud-builders/docker
  id: Push Airflow DAGs Builder
  args: [
      'push',
      'gcr.io/$PROJECT_ID/dbt-demo:latest'
    ]

- name: 'gcr.io/$PROJECT_ID/dbt-demo'
  id: dbt CI testing
  entrypoint: bash
  env:
  - 'BUILD_ID=$BUILD_ID'
  args:
  - -c
  - |
    sqlfluff lint models/report/
    dbt deps --profiles-dir .dbt --vars '{"project_id": '$PROJECT_ID',"build_id": '${BUILD_ID//-/_}'}' --target ci 
    dbt run  --vars '{"project_id": '$PROJECT_ID',"build_id": '${BUILD_ID//-/_}'}' --profiles-dir .dbt --target ci
    dbt test  --vars '{"project_id": '$PROJECT_ID',"build_id": '${BUILD_ID//-/_}'}' --profiles-dir .dbt --target ci
    dbt docs generate --vars '{"project_id": '$PROJECT_ID',"build_id": '${BUILD_ID//-/_}'}' --profiles-dir .dbt --target ci
    dbt-coverage compute doc --cov-fail-under 0.2

options:
  logging: CLOUD_LOGGING_ONLY